version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: omc
    main: ./cmd/omc
    binary: omc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X paepcke.de/omc/internal/version.Version={{.Version}}
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:

archives:
  - id: omc
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: true
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
release:
  github:
    owner: paepckehh
    name: omc
